Feature/add time manager
GP-Engine-team/GP_Engine pull request #14
Opened 2021-02-05 13:57 UTC by Renardjojo

Create a time system according to the diagram about this subject. For now, time system is not a singleton and allow the user to create timer task. This task can loop and can only be destroyed if the container is clear with the function clearScaledTimer or clearUnscaledTimer. If this feature is really useful, I will implement it

2021-02-05 16:59 UTC, Korotsu approved these changes

2021-02-09 08:34 UTC, ThomasProg commented on engine/include/Engine/Core/Rendering/Window/WindowGLFW.hpp
> +    void getSize(int width, int height) const noexcept;
Why ?

2021-02-09 08:49 UTC, ThomasProg commented on engine/src/WindowGLFW.cpp
> +void Engine::Core::Renderering::Window::getSize(int width, int height) const noexcept
Same as before : add references

2021-02-09 09:49 UTC, ThomasProg reviewed
getSize() has wrong arguments
Otherwise, valid commit.

2021-02-09 09:50 UTC, ThomasProg approved these changes

2021-02-09 11:02 UTC, Bad-Sam requested changes

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/Rendering/Window/WindowGLFW.hpp
> +    void getSize(int width, int height) const noexcept;
The new version can't return the size of the window without pointers, references, or a return value
```suggestion
    void getSize(int& width, int& height) const noexcept;
    // Or
    Math::Vec2 getSize() const noexcept;
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    std::function<void()> task = nullptr;
**TODO for later**, when `Task` will be implemented: replace `std::function<void()>` with `Task`, so functions can be stored with any number and type of argument

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    double m_fixedDetlaTime = m_fixedUnscaledDetlaTime * m_timeScale;
```suggestion
    double m_fixedUnscaledDeltaTime = 1. / 60.;
    double m_fixedDeltaTime = m_fixedUnscaledDeltaTime * m_timeScale;
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    void update(std::function<void(double fixedUnscaledDetlaTime, double fixedDetlaTime)> fixedUpdateFunction,
```suggestion
    void update(std::function<void(double fixedUnscaledDeltaTime, double fixedDeltaTime)> fixedUpdateFunction,
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +     * @param newFixedUnscaledDetlaTime
```suggestion
     * @param newFixedUnscaledDeltaTime 
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    inline void setFixedUnscaledDeltaTime(double newFixedUnscaledDetlaTime) noexcept;
```suggestion
    inline constexpr void setFixedUnscaledDeltaTime(double newFixedUnscaledDeltaTime) noexcept;
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +     * @brief Redefine time scale. This value will use to comput scaled detla time and scaled fixed delta time. Usefull to change the game speed
```suggestion
     * @brief Redefine time scale. This value will use to compute scaled delta time and scaled fixed delta time. Useful to change the game speed
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.cpp
> +void TimeSystem::update(std::function<void(double fixedUnscaledDetlaTime, double fixedDetlaTim)> fixedUpdateFunction,
```suggestion
void TimeSystem::update(std::function<void(double fixedUnscaledDeltaTime, double fixedDeltaTime)> fixedUpdateFunction,
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.cpp
> +    while (m_fixedTimeAcc >= m_fixedUnscaledDetlaTime)
```suggestion
    while (m_fixedTimeAcc >= m_fixedUnscaledDetlaTime)
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.cpp
> +        fixedUpdateFunction(m_fixedUnscaledDetlaTime, m_fixedDetlaTime);
```suggestion
        fixedUpdateFunction(m_fixedUnscaledDetlaTime, m_fixedDeltaTime);
```

2021-02-09 11:02 UTC, badsami commented on engine/src/main.cpp
> +        ts.update([&](double fixedUnscaledDetlaTime, double fixedDetlaTim)
```suggestion
        ts.update([&](double fixedUnscaledDeltaTime, double fixedDeltaTime)
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.cpp
> +        m_fixedTimeAcc -= m_fixedUnscaledDetlaTime;
```suggestion
        m_fixedTimeAcc -= m_fixedUnscaledDeltaTime;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +    return m_fixedDetlaTime;
```suggestion
    return m_fixedDeltaTime;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +    return m_fixedUnscaledDetlaTime;
```suggestion
    return m_fixedUnscaledDeltaTime;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline void Engine::Core::TimeSystem::setFixedUnscaledDeltaTime(double newFixedUnscaledDetlaTime) noexcept
```suggestion
inline constexpr void Engine::Core::TimeSystem::setFixedUnscaledDeltaTime(double newFixedUnscaledDeltaTime) noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +        Engine::Core::Debug::Log::logWarning("New fixed unscaled detla time > 1.");
```suggestion
    if (newFixedUnscaledDeltaTime > 1.)
        Engine::Core::Debug::Log::logWarning("New fixed unscaled delta time > 1.");
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +    m_fixedUnscaledDetlaTime = newFixedUnscaledDetlaTime;
```suggestion
    m_fixedUnscaledDeltaTime = newFixedUnscaledDeltaTime;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +    m_fixedDetlaTime = m_fixedUnscaledDetlaTime * m_timeScale;
```suggestion
    m_fixedDeltaTime = m_fixedUnscaledDeltaTime * m_timeScale;
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    std::chrono::system_clock::time_point m_tempTime = m_time;
According to cppreference, the time returned by `std::chrono::system_clock` can be altered, which can result in a return in time. See cppreference page [here](https://en.cppreference.com/w/cpp/chrono/system_clock#mw-content-text).

I suggest we use `std::chrono::steady_clock`, which is steady (unchanging) and monotonic (time calculated from a fixed point in time). See description [here](https://en.cppreference.com/w/cpp/chrono/steady_clock)

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    [[nodiscard]] inline double getTimeScale() noexcept;
```suggestion
    [[nodiscard]] inline constexpr double getFixedDeltaTime() const noexcept;
    [[nodiscard]] inline constexpr double getFixedUnscaledDeltaTime() const noexcept;
    [[nodiscard]] inline constexpr double getDeltaTime() const noexcept;
    [[nodiscard]] inline constexpr double getUnscaledDeltaTime() const noexcept;
    [[nodiscard]] inline constexpr double getAccumulatedTime() const noexcept;
    [[nodiscard]] inline constexpr double getAccumulatedUnscaledTime() const noexcept;
    [[nodiscard]] inline constexpr double getTimeScale() const noexcept;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline double Engine::Core::TimeSystem::getDeltaTime() noexcept
```suggestion
inline constexpr double Engine::Core::TimeSystem::getDeltaTime() const noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline double Engine::Core::TimeSystem::getUnscaledDeltaTime() noexcept
```suggestion
inline constexpr double Engine::Core::TimeSystem::getUnscaledDeltaTime() const noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline double Engine::Core::TimeSystem::getAccumulateTime() noexcept
```suggestion
inline constexpr double Engine::Core::TimeSystem::getAccumulatedTime() const noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline double Engine::Core::TimeSystem::getAccumulateUnscaledTime() noexcept
```suggestion
inline constexpr double Engine::Core::TimeSystem::getAccumulatedUnscaledTime() const noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline double Engine::Core::TimeSystem::getTimeScale() noexcept
```suggestion
inline constexpr double Engine::Core::TimeSystem::getTimeScale() const noexcept
```

2021-02-09 11:02 UTC, badsami commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    inline void setTimeScale(double newtimeScale) noexcept;
```suggestion
    inline constexpr void setTimeScale(double newtimeScale) noexcept;
```

2021-02-09 11:02 UTC, badsami commented on engine/src/TimeSystem.inl
> +inline void Engine::Core::TimeSystem::setTimeScale(double newtimeScale) noexcept
```suggestion
inline constexpr void Engine::Core::TimeSystem::setTimeScale(double newtimeScale) noexcept
```

2021-02-09 11:02 UTC, Bad-Sam commented on engine/src/TimeSystem.cpp
> +    }
I'm not sure I fully understand what this is doing, I'm sorry if I get this wrong: `m_fixedTimeAcc` is incremented by `m_unscaledDeltaTime` every time `TimeSystem::update()` is called, but it is then compared to `m_fixedUnscaledDetlaTime`. Shouldn't it be compared to `m_fixedDeltaTime` instead?

2021-02-09 11:02 UTC, Bad-Sam commented on engine/include/Engine/Core/TimeSystem/TimeSystem.hpp
> +    unsigned int m_frameAcc = 0;
`m_frameAcc` is not used anywhere.
If it is meant to be used, move it after the `double`s to align it properly

2021-02-10 08:43 UTC, Bad-Sam approved these changes

2021-02-10 08:46 UTC, merged

2021-02-10 08:46 UTC, Renardjojo commented
Done