Feature/hot reload : Files names modified, instructions added in readme
GP-Engine-team/GP_Engine pull request #18
Opened 2021-02-10 13:35 UTC by ThomasProg

2021-02-11 07:54 UTC, Renardjojo approved these changes

2021-02-11 16:26 UTC, Bad-Sam commented on engine/include/Engine/Core/Tools/Format.hpp
> -#include <memory>
I would rather see all the headers together next to each others, rather than split

2021-02-11 16:27 UTC, Bad-Sam commented on engine/src/Format.inl
> +#include <memory>
I would rather see all the headers together next to each others, rather than split

2021-02-11 17:20 UTC, Bad-Sam requested changes
I was a few other points in the files of feature/hotReload which I would like to review. These files don't appear here for some reason, so I'll just make a new branch with changes suggestions and open a pull request

2021-02-11 17:20 UTC, badsami commented on launcher/gameStartup.cpp
> +	GPE_ASSERT(m_game != nullptr, "m_game should be valid since we're running the game.");
This should be moved to the constructor

2021-02-11 17:20 UTC, badsami commented on launcher/gameStartup.cpp
>  	std::function<void()> render = std::bind(&AbstractGame::render, m_game);
I would move those 3 `std::function`s as data members, and generate them once in the constructor

2021-02-11 17:20 UTC, Bad-Sam commented on projects/GPGame/README.md
>  - 3 : Run [installer](install_dependancies.bat) in the project root to download dependancy (git submodule) and install it
```suggestion
2. Run CMake's installer and check "Add CMake to the system path" (for all/current user)
![](https://tulip.labri.fr/TulipDrupal/sites/default/files/uploadedFiles/users/6/screenshot_cmake01.png)
3. Run the [install_dependancies.bat](install_dependancies.bat) script in the project root to download dependencies (as submodules) and install them
```

I would also rename the script `install_dependancies.bat` to `install_dependencies.bat`. There is currently no such script in your branch.

This README should be at the root of the project.

Line 8, I would also replace :

> Run this command to download all dependencies (this operation can take up to a few minutes)
> ```batch
> git submodule update --init --recursive
> ```

with 

> Start by cloning the project with
> ```
> `git clone --recurse-submodules https://github.com/GP-Engine-team/GP_Engine.git`
> ```
> (this operation can take up to a few minutes)

which will initialize all submodules immediatly

2021-02-11 17:20 UTC, Bad-Sam commented on projects/GPGame/README.md
> +If you want to use the hot reload, you have different methods :
```suggestion
If you want to use hot reload, you have 2 choices:
```

2021-02-11 17:20 UTC, Bad-Sam commented on projects/GPGame/README.md
> +- You can run in debug mode (f5) and then rebuild the dll (ctrl + maj + b) with another visual studio instance each time you change it.
```suggestion
- You can run without debug mode (Ctrl + F5) and then rebuild the dll (Ctrl + maj + B) each time you change it.
- You can run in debug mode (F5) and then rebuild the dll (Ctrl + maj + B) with another Visual Studio instance each time you change it.
```

2021-02-15 08:57 UTC, Bad-Sam approved these changes

2021-02-16 09:13 UTC, merged