Feature/behaviour manager
GP-Engine-team/GP_Engine pull request #25
Opened 2021-02-22 15:15 UTC by Renardjojo

Create behaviour system and behaviours component that allow user to define behaviour for its entities

2021-02-22 15:16 UTC, Renardjojo commented
I also push little improve in texture class

2021-02-24 09:40 UTC, Korotsu approved these changes

2021-02-24 10:07 UTC, Bad-Sam commented on engine/src/BehaviourSystem.cpp
> +    m_updateFunctions.emplace_back(updateFunction);
```suggestion
    m_updateFunctions.push_back(updateFunction);
```

2021-02-24 10:14 UTC, merged

2021-02-24 10:14 UTC, ThomasProg approved these changes

2021-02-24 10:14 UTC, ThomasProg commented on engine/src/Texture.cpp
> +    if (m_comp == 1)
Use a switch

2021-02-24 11:07 UTC, badsami requested changes

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    m_updateFunctions.emplace_back(fixedUpdateFunction);
```suggestion
    m_fixedUpdateFunctions.push_back(fixedUpdateFunction);
```

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    }
```suggestion
    for (BehaviourComponent*& function : m_fixedUpdateFunctions)
    {
        if (unlikely(function == fixedUpdateFunctionToRemove))
        {
            std::swap(function, m_fixedUpdateFunctions.back());
            m_fixedUpdateFunctions.pop_back();
            return;
        }
    }
```

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    m_updateFunctions.emplace_back(updateFunction);
There doesn't seem to be a mechanism or check to prevent a `BehaviourComponent*` from being added twice to `m_updateFunctions`.

A test on `updateFunction` seems necessary here

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    m_updateFunctions.emplace_back(fixedUpdateFunction);
There doesn't seem to be a mechanism or check to prevent a `BehaviourComponent*` from being added twice to `m_fixedUpdateFunctions`.

A test on `fixedUpdateFunction` seems necessary here

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +        }
```suggestion
            m_updateFunctions.pop_back();
            return;
        }
```

2021-02-24 11:07 UTC, badsami commented on engine/include/Engine/Intermediate/BehaviourComponent.inl
> +}
Calling `enableUpdate()` several times in a row will call `BehaviourSystem::addUpdate()` several times, which is problematic. The same goes for `BehaviourComponent::enableFixedUpdate()`

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    for (std::vector<BehaviourComponent*>::iterator it = m_pBehaviours.begin(); it != m_pBehaviours.end(); it++)
```suggestion
    const std::vector<BehaviourComponent*>::iterator end = m_pBehaviours.end();
    for (std::vector<BehaviourComponent*>::iterator it = m_pBehaviours.begin(); it != end; ++it)
```

Since the size and location of the data are not changed, `m_pBehaviours.end()` will remain constant

2021-02-24 11:07 UTC, badsami commented on engine/include/Engine/Intermediate/BehaviourSystem.hpp
> +    std::vector<BehaviourComponent*>  m_pBehaviours;
`BehaviourComponent`s are already stored in a `DataChunk<BehaviourComponent>`. Would it be ok to use a pointer to that chunk, rather than storing the same components again?

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +                                             BehaviourComponent* exPointorBehaviour) noexcept
```suggestion
void BehaviourSystem::updateBehaviourPointer(BehaviourComponent const* newPointorBehaviour,
                                             const BehaviourComponent* exPointorBehaviour) noexcept
```

I'm not 100% sure for `BehaviourComponent const* newPointorBehaviour`, it should be tested first

2021-02-24 11:07 UTC, badsami commented on engine/src/BehaviourSystem.cpp
> +    for (std::vector<BehaviourComponent*>::iterator it = m_pBehaviours.begin(); it != m_pBehaviours.end(); it++)
```suggestion
    const std::vector<BehaviourComponent*>::iterator end = m_pBehaviours.end();
    for (std::vector<BehaviourComponent*>::iterator it = m_pBehaviours.begin(); it != end ; ++it)
```